name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update apt
        run: sudo apt-get -y update

      - name: Install sdcc
        run: sudo apt-get install -y sdcc

      - name: Run make bin
        run: make bin

      - name: Run make hex
        run: make hex

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: |
            touch.bin
            touch.hex
